// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vqffehsaiufhwapqngrg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZxZmZlaHNhaXVmaHdhcHFuZ3JnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI3MjkwNDQsImV4cCI6MjA1ODMwNTA0NH0.rMeC__42dus0cxqhgtstjAHM_d_uPKma_y5Xmm7K5rU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);